"""phase9 initial tables

Revision ID: 183123584310
Revises: 
Create Date: 2026-06-22 23:05:21.641858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183123584310'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.Column('first_seen_ts', sa.Float(), nullable=False),
    sa.Column('emitted_ts', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('violation_class', sa.String(length=64), nullable=False),
    sa.Column('violation_conf', sa.Float(), nullable=False),
    sa.Column('person_bbox', sa.JSON(), nullable=False),
    sa.Column('violation_bbox', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule', 'person_id', 'frame', 'source', name='uq_event_rule_person_frame_source')
    )
    with op.batch_alter_table('violation_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_rule_emitted', ['rule', 'emitted_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_events_emitted_ts'), ['emitted_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_events_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_events_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_events_source'), ['source'], unique=False)

    op.create_table('alert_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sink', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=False),
    sa.Column('dispatched_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['violation_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_dispatches_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_dispatches_sink'), ['sink'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_dispatches_success'), ['success'], unique=False)

    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['violation_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_files_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_files_event_id'))

    op.drop_table('evidence_files')
    with op.batch_alter_table('alert_dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_dispatches_success'))
        batch_op.drop_index(batch_op.f('ix_alert_dispatches_sink'))
        batch_op.drop_index(batch_op.f('ix_alert_dispatches_event_id'))

    op.drop_table('alert_dispatches')
    with op.batch_alter_table('violation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_events_source'))
        batch_op.drop_index(batch_op.f('ix_violation_events_rule'))
        batch_op.drop_index(batch_op.f('ix_violation_events_person_id'))
        batch_op.drop_index(batch_op.f('ix_violation_events_emitted_ts'))
        batch_op.drop_index('ix_event_rule_emitted')

    op.drop_table('violation_events')
    # ### end Alembic commands ###
